### PR TITLE
bump to python >=3.8

### PR DESCRIPTION
**Pull request by jameslamb**
As of #55, conda-forge is distributing `v0.20.2` of this package.

Since https://github.com/xflr6/graphviz/pull/202, the `graphviz` Python package has had a floor of `python >= 3.8`. This proposes updating the recipe here to match.

## Benefits of this change

Prevents `v0.20.2` from being pulled into Python 3.7 environments.

`v0.20.2` contains code that is not syntactically valid Python 3.7.

```shell
conda create \
    --name test-env \
    -c conda-forge \
    --yes \
        python=3.7 python-graphviz

source activate test-env
python -c "import graphviz"
```

```text
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jlamb/miniforge/envs/test-env/lib/python3.7/site-packages/graphviz/__init__.py", line 31, in <module>
    from .backend import (DOT_BINARY, UNFLATTEN_BINARY,
  File "/Users/jlamb/miniforge/envs/test-env/lib/python3.7/site-packages/graphviz/backend/__init__.py", line 5, in <module>
    from .mixins import Render, Pipe, Unflatten, View
  File "/Users/jlamb/miniforge/envs/test-env/lib/python3.7/site-packages/graphviz/backend/mixins.py", line 8, in <module>
    from . import piping
  File "/Users/jlamb/miniforge/envs/test-env/lib/python3.7/site-packages/graphviz/backend/piping.py", line 5, in <module>
    from .. import _tools
  File "/Users/jlamb/miniforge/envs/test-env/lib/python3.7/site-packages/graphviz/_tools.py", line 23
    def attach(object: typing.Any, /, name: str) -> typing.Callable:
                                   ^
SyntaxError: invalid syntax
```

## Checklist

* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

## Notes for Reviewers

Noticed this in CI for `lightgbm`, where we are still trying to do some testing with Python 3.7 and to use conda-forge to create environments: https://github.com/microsoft/LightGBM/pull/6370.

I'm not proposing a repodata patch, as I know conda-forge is no longer supporting Python 3.7 (https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/478#pullrequestreview-1523437604). But hope this PR could be merged... I think it'd be a low-risk way to prevent others from encountering this import error.

Thanks for your time and consideration.

### CODE REVIEW

**Comment by jameslamb** [comment]
@conda-forge-admin, please rerender

**Comment by jameslamb** [comment]
@conda-forge-admin, please rerender

**Comment by jameslamb** [comment]
At this point even Python 3.8 is just a few hours from end-of-life (https://devguide.python.org/versions/), so people building new Python `<=3.7` environments with conda-forge packages should be even rarer than it was when this PR was opened 6 months ago. Suspect that's why this and #58 don't have any new comments or cross-links in that time.

That said, I do still think this is a good and low-risk change. I'll leave this up for another month or two to see if feedstock maintainers here have any interest in pursuing it, and then close it if they say no or don't respond.

**Comment by jakirkham** [comment]
Oops sorry for missing this. Thanks James! 🙏

Could you please also add a repodata patch for the 0.20.2 and older 0.20.3 packages? Here is [a good starting point]( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/f08fe33dcc91b415605267588950acbe16717950/recipe/patch_yaml/zipp.yaml#L27-L35 )

**Comment by jameslamb** [comment]
No problem, thanks @jakirkham !

Created the repodata patch here: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/868

**Pull request merged**
