### PR TITLE
RFC: Use noarch

### PR DESCRIPTION
**Pull request by jakirkham**
Switch the recipe over to noarch Python. Also always apply the Windows patch so as to allow for the noarch Python build.

### CODE REVIEW

**Comment by jakirkham** [comment]
Could you please take a look @xflr6? Would like to hear what you think. 😄

**Comment by xflr6** [comment]
Thanks. Applying the patch with the Windows branch everywhere for a platform-agnostic conda package seems good to me (do not know much about the build tool used here though). AFAICT, the [build for this PR](https://circleci.com/gh/conda-forge/python-graphviz-feedstock/51) currently still fails:

```
Applying patch: '/recipe_root/windows-bat.patch'
patching file graphviz/backend.py
Hunk #1 FAILED at 85.
1 out of 1 hunk FAILED -- saving rejects to file graphviz/backend.py.rej
```

I suspect there is still the issue of how to patch a file with CRLF line endings within `conda-build` (see conda/conda-build#1973): On the windows-specific branch there is currently some trial and error to get this working (I would prefer if one could just have the option to configure `patch --binary` as proposed in issue 1973 mentioned above, e.g. by having a special ending):

https://github.com/conda/conda-build/blob/de49f28806a20e251ad0a54c3ae4da0c49dd0a1d/conda_build/source.py#L563-L595

**Comment by jakirkham** [comment]
Tried to [manually apply the patch]( https://github.com/jakirkham-feedstocks/python-graphviz-feedstock/blob/796283c73282b34180d63a73291bdd887a1a1ca8/recipe/build.sh#L7 ), but it ran into some issues.

**Comment by jakirkham** [comment]
Replacing with PR ( https://github.com/conda-forge/python-graphviz-feedstock/pull/23 ).

**Pull request closed without merging**
